// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5dLzn5BQyAfngQEm32Rca0ZmvszF9K2o',
    appId: '1:873394852333:web:fe7d140cfd4533a54817e4',
    messagingSenderId: '873394852333',
    projectId: 'smart-daily-planner-sdp',
    authDomain: 'smart-daily-planner-sdp.firebaseapp.com',
    storageBucket: 'smart-daily-planner-sdp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEkIBahHpWyj7d2gdOU8S1O-VYvDjJfEM',
    appId: '1:873394852333:android:1682d84c9c3c121e4817e4',
    messagingSenderId: '873394852333',
    projectId: 'smart-daily-planner-sdp',
    storageBucket: 'smart-daily-planner-sdp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeYC-PIDy6hktagzZr-ekaJzbsJhKvkls',
    appId: '1:873394852333:ios:dbcc46210810efe84817e4',
    messagingSenderId: '873394852333',
    projectId: 'smart-daily-planner-sdp',
    storageBucket: 'smart-daily-planner-sdp.firebasestorage.app',
    iosBundleId: 'com.example.smartDailyPlanner',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeYC-PIDy6hktagzZr-ekaJzbsJhKvkls',
    appId: '1:873394852333:ios:dbcc46210810efe84817e4',
    messagingSenderId: '873394852333',
    projectId: 'smart-daily-planner-sdp',
    storageBucket: 'smart-daily-planner-sdp.firebasestorage.app',
    iosBundleId: 'com.example.smartDailyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5dLzn5BQyAfngQEm32Rca0ZmvszF9K2o',
    appId: '1:873394852333:web:55353943745c39324817e4',
    messagingSenderId: '873394852333',
    projectId: 'smart-daily-planner-sdp',
    authDomain: 'smart-daily-planner-sdp.firebaseapp.com',
    storageBucket: 'smart-daily-planner-sdp.firebasestorage.app',
  );
}
